banken-paopao/nagano_cake

app/models/address.rb, app/models/cart_item.rb, app/models/genre.rb, app/models/item.rb, app/models/order.rb, app/models/order_detail.rb, db/migrate/20220715011939_create_addresses.rb, db/migrate/20220715012513_create_items.rb, db/migrate/20220715013004_create_genres.rb, db/migrate/20220715013412_create_cart_items.rb, db/migrate/20220715013939_create_orders.rb, db/migrate/20220715014428_create_order_details.rb, db/schema.rb, test/fixtures/addresses.yml, test/fixtures/cart_items.yml, test/fixtures/genres.yml, test/fixtures/items.yml, test/fixtures/order_details.yml, test/fixtures/orders.yml, test/models/address_test.rb, test/models/cart_item_test.rb, test/models/genre_test.rb, test/models/item_test.rb, test/models/order_detail_test.rb, test/models/order_test.rb
=> テーブルの作成をしました

app/models/address.rb, app/models/cart_item.rb, app/models/customer.rb, app/models/genre.rb, app/models/item.rb, app/models/order.rb, app/models/order_detail.rb
=> アソシエーションの追加

app/views/public/registrations/new.html.erb
- 会員の新規登録画面を作成しました。
- Bootstrapのclassを適当に書いてあります。
- 確認お願いします。
=> Customer registration

Gemfile, Gemfile.lock, app/models/address.rb, app/models/admin.rb, app/models/application_record.rb, app/models/cart_item.rb, app/models/customer.rb, app/models/genre.rb, app/models/item.rb, app/models/order.rb, app/models/order_detail.rb, config/environments/development.rb, config/routes.rb, lib/tasks/auto_annotate_models.rake, test/fixtures/addresses.yml, test/fixtures/admins.yml, test/fixtures/cart_items.yml, test/fixtures/customers.yml, test/fixtures/genres.yml, test/fixtures/items.yml, test/fixtures/order_details.yml, test/fixtures/orders.yml, test/models/address_test.rb, test/models/admin_test.rb, test/models/cart_item_test.rb, test/models/customer_test.rb, test/models/genre_test.rb, test/models/item_test.rb, test/models/order_detail_test.rb, test/models/order_test.rb
=> デバッグ用のgemの追加

app/controllers/public/registrations_controller.rb, app/controllers/public/sessions_controller.rb, app/views/public/sessions/new.html.erb
- ログイン画面の編集
- controllerでログイン先のログアウト先の追加
確認お願いします
=> [add]会員ログイン機能の追加

app/javascript/packs/application.js, app/javascript/stylesheets/application.scss, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, config/webpack/environment.js, package.json, yarn.lock
- bootstrap追加
- ヘッダー追加
確認お願いします！
=> bootstrap ヘッダー追加

app/controllers/admin/genres_controller.rb, app/views/admin/genres/edit.html.erb
- genreのeditページ
- genreのupdate機能
ご確認お願いします
=> [Add]genreの編集ページの追加

app/controllers/admin/items_controller.rb, app/javascript/packs/application.js, app/models/item.rb, app/views/admin/items/create.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/update.html.erb
- indexページの実装
- newページの実装
- create機能の実装
___
ご確認お願いします
=> [Add]itemのindexページnewページcreate機能の作

app/controllers/admin/genres_controller.rb, app/controllers/admin/items_controller.rb, app/javascript/packs/application.js, app/models/item.rb, app/views/admin/genres/create.html.erb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/genres/update.html.erb, app/views/admin/items/create.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/update.html.erb
=> Adminからdevelopへのマージ

app/controllers/admin/items_controller.rb, app/views/admin/items/show.html.erb
- showページのviewとコントローラーを作成しました。
_into admin from admin-item-show_
**ご確認お願いします！**
=> [Add]商品の詳細ページ作成しました

app/controllers/admin/items_controller.rb, app/views/admin/items/edit.html.erb
- editページの追加
- update機能の追加
_into admin form admin-item-edit_
ご確認お願いします
=> [Add]itemのeditページupdate機能の追加

app/controllers/admin/items_controller.rb, app/views/admin/items/edit.html.erb, app/views/admin/items/show.html.erb
まとまった機能が実装できましたのでご確認お願いします
___
_into develop from admin_
=> into develop from admin

app/controllers/admin/customers_controller.rb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, db/seeds.rb
- 会員一覧画面(Admin)
- 会員詳細画面(Admin)
- 会員情報をseedに追加
確認お願いします!
**from   admin-customer-view    to    admin**
=> Admin側の会員画面と会員情報のseed 追加

app/controllers/public/cart_items_controller.rb, app/models/cart_item.rb, app/models/customer.rb, app/models/item.rb, app/views/public/cart_items/index.html.erb, config/routes.rb
カートの一覧画面とコントローラーを作りました
カスタマーにカスタマーカートアイテムズをマージしたいです
=> Cart itemsのページを作成

app/views/admin/sessions/new.html.erb
- レイアウト調整をしました
- 一旦、adminにマージします
_into admin from admin-top-layout_
=> [Update]adminのsigninページのレイアウト変更

app/controllers/public/customers_controller.rb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb
カスタマーマイページと編集画面を追加しました
customerにcustomer-my-pageをマージします
=> [Add]customoer-マイページと編集画面の追加

app/controllers/admin/customers_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/show.html.erb
- 会員編集画面作成
- 会員詳細画面編集
確認お願いします
=> Admin側　会員画面

app/controllers/public/customers_controller.rb, app/controllers/public/sessions_controller.rb, app/views/public/customers/unsubscribe.html.erb
退会画面と退会フラグを作成しました。
**customerにcustomer-my-pageをマージします**
=> [Add]退会画面と退会フラグの作成

app/controllers/admin/homes_controller.rb, app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/views/admin/homes/top.html.erb, app/views/admin/orders/show.html.erb
- 注文一覧画面(余裕できたら個人の履歴画面追加します)
- 注文詳細画面
確認お願いします
**from admin-order-view to admin**
=> Admin側　注文履歴画面追加

app/controllers/public/items_controller.rb, app/views/public/items/show.html.erb
- 商品詳細ページを作成しました
- 確認お願いします
- customerにcustomer-item/showをマージします
=> 会員側の商品詳細ページ

app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb
- index
- edit
- レイアウト調整
into admin from admin-genre-layout
=> genreのレイアウト調整

app/models/customer.rb
- 漢字とカナをそれぞれ結合するメゾットを追加
from admin-customer-view to admin
=> 名前結合メゾットを追加しました

app/views/public/homes/about.html.erb
- 写真はまだ貼り付けていません
- 16行目に写真を入れる予定で空けてあります
- customerにcustomer-home-about をマージします
=> [Add]Aboutページ写真なし

Gemfile, Gemfile.lock, app/models/item.rb, app/models/order.rb, app/models/order_detail.rb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, config/application.rb, config/locales/ja.yml
- index
- show
- new
- edit
レイアウト調整しましたので、ご確認お願いします。
_into admin from admin-item-layout_
admin-item-layoutからadminへ
=> [Update]admin側のitemページのレイアウト調整

app/models/order_detail.rb, app/views/admin/customers/index.html.erb, app/views/admin/orders/show.html.erb
- ステータスemunに適応
- 退会ステータスのコード修正
- 金額のコードの修正
確認お願いします！
**from admin-customer-view to admin**
=> 注文履歴画面編集,金額メゾットの追加

app/models/order.rb, app/views/admin/orders/show.html.erb
- 住所を結合するメゾット追加しました
- 注文詳細画面の表示おかしかったので修正しました
確認お願いします
**from admin-customer-view into admin**
=> [Add]住所結合メゾット追加

app/controllers/public/homes_controller.rb, app/views/public/homes/top.html.erb
- トップページを作りました
- メイン画像はまだ制作していません
- customerからcustomer-homeにマージしました
=> [Add]トップページを作成

app/views/public/homes/top.html.erb, app/views/public/items/_genre.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb
- 会員の商品一覧と詳細、トップページの部分テンプレート作成しました
- トップページのclassがclasになっていたので修正しました
確認お願いします
customerからcustomer-genreのマージです
=> [Add]Genreの部分テンプレート

app/controllers/public/cart_items_controller.rb
表題の通りです
controllerのcreateが抜けてたので入れました
customerにcustomer-cart-itemsをマージします
=> [Add]cart-itemにitemを追加できるようにしました

app/views/public/cart_items/index.html.erb
カートのインデックスページのレイアウトを整えました
customerにcustomer-cart-items-layoutをマージします
=> [Update]cart-item-viewレイアウト更新

app/controllers/admin/orders_controller.rb, app/views/admin/customers/show.html.erb, app/views/admin/orders/history.html.erb, app/views/admin/orders/show.html.erb, config/routes.rb
- 新たにadmin/orders/history.html.erbファイルの追加
- ルーティングの追加
- 変数のコード変更
- 変数のコード変更に伴いビューの編集
確認お願いします！
from admin-customer-view into admin
=> 会員別注文履歴画面追加

.bash_profile, app/views/public/addresses/index.html.erb
配送先一覧のレイアウトを追加しました
プレースホルダを追記しました
=> 配送先一覧のレイアウト

app/javascript/packs/application.js, app/javascript/stylesheets/application.scss, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb, package.json, yarn.lock
ご確認お願いします
footer-create　⇒　develop
=> [Add]Footerの作成

app/views/public/addresses/edit.html.erb
配送先の編集画面のレイアウト作成しました
form_withのmethodがpostになっていたのをpatchに変更しました
確認お願いします
customerからcustomer-addresses-editにマージします
=> [Add]配送先編集画面レイアウト

app/javascript/stylesheets/application.scss, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb
=> [Fix]修正しました

app/views/public/orders/new.html.erb
注文情報登録画面のレイアウトを整えました
customerにcustomer-orders-layoutをマージします
=> [Update]注文情報登録画面のレイアウトを更新

app/views/public/orders/new.html.erb
注文ができないバグを直しました
debugにcustomer-order-fixをマージします
=> [Fix]customer-order-new画面の確認画面に進めないバグ

app/controllers/application_controller.rb, app/javascript/stylesheets/application.scss, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/homes/top.html.erb, app/views/admin/items/show.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb
- root_pathとadmin_pathのいずれかに遷移
- ロゴを押すといずれかに遷移
確認お願いします
fix-layout　⇒　debug
=> [Update]ログイン後の遷移先やレイアウト調整

app/javascript/stylesheets/application.scss, app/views/admin/customers/edit.html.erb
- 住所フォーム短かったので伸ばしました
- タイトルのレイアウト調整しました
確認お願いします
from debug-customer-view into debug
=> 住所フォームレイアウト変更

app/views/public/orders/new.html.erb
- 選択範囲を拡大しました！
確認お願いします。
customer-update => debug
=> [Update]radioボタンの選択範囲の拡大

app/javascript/stylesheets/application.scss, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
- imageの位置も多分大丈夫ですが確認お願いします
- 細いですがいい感じだと思います
確認お願いします！
common => common-update
=> [Update]headerの位置とflashメッセージの編集

app/controllers/admin/orders_controller.rb, app/views/admin/orders/history.html.erb
表示がおかしいバグ修正しました
確認お願いします
from debug-customer-view into debug
=> [Edit]会員別一覧コード編集

app/views/layouts/_header.html.erb
ヘッダーにようこそ○○さん追加を追加しました
確認お願いします
debug-header-view > debug
=> [Add]ようこそ○○さん追加

app/views/public/orders/confirm.html.erb, app/views/public/orders/new.html.erb
new-orderのcontainerを修正
confilm-orderのレイアウトを整えました
確認お願いします
debugにdebug-customer-orders-layoutをマージします
=> [Update]naw-order comfilm-oder layout

app/javascript/stylesheets/application.scss, app/views/layouts/_header.html.erb
=> [Fix]headerの修正

app/javascript/stylesheets/application.scss
=> [Update]ハンバーガーメニューのボタンの色を変更

app/controllers/admin/genres_controller.rb, app/views/admin/genres/_form.html.erb, app/views/admin/genres/_index.html.erb, app/views/admin/genres/create.js.erb, app/views/admin/genres/index.html.erb
- 非同期化処理になってます
確認お願いします
admin-update => debug
=> [Update]genreにajaxの適用

app/models/customer.rb, app/views/admin/customers/edit.html.erb
last_name first_nameのコード入れ替えました
確認お願いします
debug-admin-name > debug
=> [Edit]氏名コード編集

app/controllers/public/items_controller.rb, app/models/item.rb, app/views/public/items/_genre.html.erb, app/views/public/items/genre_search.html.erb, config/routes.rb
ジャンル検索機能追加しました
Items/modelを追記しました
ルーティングも追記しました
新しくgenre_search.html.erbページを作成しました
debugからdebug-genreにマージします
確認お願いします
=> [Add]ジャンル検索機能

app/views/public/items/item_search.html.erb, app/views/public/items/show.html.erb
=> [Fix]検索画面の挙動修正

app/views/public/cart_items/index.html.erb
=> [Fix]cart-itemsテーブルヘッダーの価格

app/controllers/admin/homes_controller.rb, app/controllers/admin/orders_controller.rb
=> [Edit]降順修正

app/views/public/items/show.html.erb
税込価格に編集
debugからdebug-item-showにマージします
=> [Add]税込価格に修正

app/javascript/stylesheets/application.scss, app/views/admin/genres/_form.html.erb, app/views/admin/genres/_index.html.erb, app/views/admin/items/_form.html.erb, app/views/public/items/_genre.html.erb
- ボタンのテンプレートカラーを作成しました
admin-update => debug
=> [Update]ボタンの色のテンプレートを作成しました

app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb
フラッシュメッセージと被らないように変更しました
debugからdebug-addressにマージします
=> [Add]配送先ページのレイアウト変更

config/environments/development.rb
エラー発生時のレイアウト崩れを修正するコード追加しました
debug-error >> debug
=> [Add]エラー発生時のレイアウト崩れ修正

app/controllers/admin/customers_controller.rb, app/controllers/admin/genres_controller.rb, app/controllers/admin/homes_controller.rb, app/controllers/admin/items_controller.rb, app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/controllers/public/addresses_controller.rb, app/controllers/public/cart_items_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/orders_controller.rb, app/views/public/orders/new.html.erb, config/locales/ja.yml
- controllerに追加しました
- カートの2番目の選択肢を登録されていなければ選べないようにしました
=> [Fix]before_actionの追加

app/controllers/application_controller.rb
- adminはログアウト後にsign_inページにリダイレクトします
=> [Update]ログアウト後の遷移先の設定

app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb, app/views/public/items/item_search.html.erb
ログインしていなくても、商品詳細ページにアクセスできるようにしました
debugからdebug-itemlinkにマージします
=> [Add]商品詳細へのアクセス

app/controllers/public/cart_items_controller.rb, app/models/order.rb, app/views/public/orders/confirm.html.erb, app/views/public/orders/new.html.erb
shipping_costをモデルに追加しました
800と書いてあったところをメソッドの呼び出しに変更しました
確認お願いします
漏れがあったらごめんなさい、連絡待ってます
debgu <= debug-order-sipping-cost
=> [Add]default-sipping-costモデルに追加

app/javascript/stylesheets/application.scss
=> [Update]背景カラーの変更

app/javascript/stylesheets/application.scss, app/views/public/sessions/new.html.erb
=> [Update]会員ログイン画面の変更

app/javascript/stylesheets/application.scss, app/views/public/registrations/new.html.erb
- カードタイプにしました
- 小さいサイズのレスポンシブ対応していません
_common-update => debug_
=> [Update]新規登録画面の変更

app/controllers/public/homes_controller.rb, app/views/public/homes/top.html.erb
トップページを最新の４つの並び替えに変更しました
商品一覧ページののボタンを変更しました
debugからdebug-topsにマージします
=> [Add]新着順に並び替え

app/controllers/public/homes_controller.rb, app/javascript/packs/application.js, app/javascript/packs/slick.js, app/javascript/stylesheets/application.scss, app/views/layouts/application.html.erb, app/views/public/homes/top.html.erb
- ほぼ導入しただけです
_add-slick => debug_
=> [Add]slickの導入

app/javascript/packs/slick.js, app/views/public/homes/top.html.erb
=> [Fix]トップ画面の商品一覧の表示の修正

app/javascript/stylesheets/application.scss, app/views/public/customers/show.html.erb
マイページのレイアウトを調整しました
確認お願いします
debug-view-wdit >> debug
=> [Edit]レイアウト調整

app/controllers/public/cart_items_controller.rb, app/models/customer.rb, app/views/public/cart_items/destroy.js.erb, app/views/public/cart_items/destroy_all.js.erb, app/views/public/cart_items/index.html.erb, app/views/public/cart_items/update.html.erb, app/views/public/cart_items/update.js.erb, app/views/public/orders/confirm.html.erb
cart-itemを非同期通信化しました
確認お願いします
debug <= debug-cart-item-ajax
=> [Update]cart-items-ajax

app/javascript/stylesheets/application.scss, app/views/public/customers/show.html.erb, app/views/public/orders/index.html.erb
注文一覧画面のレイアウト調整しました
確認お願いします
debug-view-edit >> debug
=> [Edit]注文一覧画面レイアウト調整

app/javascript/packs/slick.js, app/javascript/stylesheets/application.scss, app/views/public/homes/top.html.erb, app/views/public/registrations/new.html.erb
- ジャンルをサイドバーのようにしました
- 浮き上がります
**[Fix]新規登録画面の下部のラインを修正**
_common-update => debug_
=> [Update]topページの変更

app/javascript/stylesheets/application.scss, app/views/public/items/index.html.erb
=> [Fix]min-widthの削除

app/javascript/stylesheets/application.scss, app/javascript/stylesheets/button.scss, app/models/item.rb, app/views/admin/genres/_form.html.erb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/items/_form.html.erb, app/views/admin/items/show.html.erb, app/views/admin/sessions/new.html.erb, app/views/public/homes/about.html.erb, app/views/public/homes/top.html.erb, app/views/public/sessions/new.html.erb, app/views/public/shared/_error_messages.html.erb
- ジャンル一覧ページのレイアウト調整
- btn関連のscssのファイルの移動
=> [Update]レイアウト調整

app/assets/stylesheets/public/favorites.scss, app/controllers/public/favorites_controller.rb, app/helpers/public/favorites_helper.rb, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/favorite.scss, app/models/customer.rb, app/models/favorite.rb, app/models/item.rb, app/views/public/customers/show.html.erb, app/views/public/favorites/_favorite.html.erb, app/views/public/favorites/_favorite_index.html.erb, app/views/public/favorites/create.js.erb, app/views/public/favorites/destroy.js.erb, app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb, config/routes.rb, db/migrate/20220721201707_create_favorites.rb, db/schema.rb, test/controllers/public/favorites_controller_test.rb, test/fixtures/favorites.yml, test/models/favorite_test.rb
- トップページ
- 一覧ページ
- showページ
- マイページ
add-favorite => debug
=> [Add]お気に入り機能の追加

app/javascript/stylesheets/favorite.scss, app/views/admin/customers/update.html.erb, app/views/admin/order_details/update.html.erb, app/views/admin/orders/update.html.erb, app/views/public/cart_items/create.html.erb, app/views/public/cart_items/index.html.erb, app/views/public/customers/update.html.erb, app/views/public/customers/withdraw.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb, app/views/public/orders/complete.html.erb, app/views/public/orders/confirm.html.erb, app/views/public/orders/create.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/new.html.erb
=> [Update]ボタンの色の修正

app/views/public/cart_items/index.html.erb, app/views/public/cart_items/update.js.erb
cart-item-indexの合計金額三桁カンマが抜けていたので追加しました
debug <= debug-cart-item-ajax
=> [Fix]合計金額の三桁カンマの抜け

app/controllers/admin/orders_controller.rb, app/views/admin/orders/history.html.erb
adminのカスタマー注文履歴のバグ修正
order-controllerのshowアクション修正
order-history-view修正
debug <= debug-adomin-orderhistory
確認お願いします
=> [Fix]カスタマー注文履歴

app/controllers/public/orders_controller.rb, app/views/public/orders/new.html.erb
order_controllerのconfilmに住所の判定を追加
order_newのviewにエラーメッセージが出るようにした
debug <= debug-order-error
確認お願いします
=> [Update]注文情報入力画面で新しい住所の中身を判定してエラーを出せるようにした

app/controllers/admin/orders_controller.rb, app/controllers/public/addresses_controller.rb, app/controllers/public/orders_controller.rb, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/button.scss, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/homes/top.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/orders/history.html.erb, app/views/admin/orders/show.html.erb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb, app/views/public/customers/edit.html.erb
=> [update]カラー調整

app/views/layouts/_header.html.erb
=> [Update]アイコンの挿入

app/views/public/homes/top.html.erb
ログイン時には子供非表示にしてます
debug-top-edit >> debug
=> [Edit]ログイン時に子供非表示

app/javascript/stylesheets/application.scss, app/javascript/stylesheets/sign_up.scss
=> [update]sign_upページのscssフォルダの作成

app/models/application_record.rb, app/models/cart_item.rb, app/models/order_detail.rb
=> [Edit]モデル修正

app/views/admin/items/_form.html.erb, app/views/admin/orders/show.html.erb
adminのviewをみんなで確認しました
インデントと合計金額を修正しました
debug <= debug-admin-views
=> [Fix]adminのインデントとか記述の修正

app/views/public/addresses/_form.html.erb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb, app/views/public/cart_items/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/customers/unsubscribe.html.erb, app/views/public/favorites/_favorite_index.html.erb
=> [Edit]コード修正

app/controllers/public/items_controller.rb, app/views/public/homes/about.html.erb, app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb, app/views/public/items/item_search.html.erb, app/views/public/items/show.html.erb, app/views/public/orders/confirm.html.erb, app/views/public/orders/new.html.erb, app/views/public/orders/show.html.erb, app/views/public/registrations/new.html.erb
=> [Update]customerのレイアウト調整

app/views/admin/items/show.html.erb
商品説明に長文を入れるとレイアウトが崩れるのを修正
develop <= debug-layout
確認お願いします
=> [Fix]admin/items/show.htmlレイアウト修正

app/javascript/stylesheets/common.scss
- 縦横比調整
common-update => develop
=> [Fix]slickの画像調整
